# Generated by Django 5.2 on 2025-04-14 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_address_remove_items_item_image_alter_items_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimages',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.items'),
        ),
    ]
