# Generated by Django 5.2 on 2025-04-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimages',
            options={'verbose_name': 'Item Image', 'verbose_name_plural': 'Item Images'},
        ),
    ]
