# Generated by Django 5.2.1 on 2025-06-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_itemimages_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='time_lost_found',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='date_lost_found',
            field=models.DateField(blank=True, null=True),
        ),
    ]
