# Generated by Django 5.2.1 on 2025-06-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_items_time_lost_found_alter_items_date_lost_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='brand',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
