# Generated by Django 5.2.1 on 2025-06-15 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_messagefile_created_at_messageimage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagefile',
            name='file',
            field=models.FileField(upload_to='files/messages/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='messagefile',
            name='message',
            field=models.ForeignKey(blank=None, null=None, on_delete=django.db.models.deletion.CASCADE, related_name='messagefiles', to='api.message'),
        ),
        migrations.AlterField(
            model_name='messageimage',
            name='message',
            field=models.ForeignKey(blank=None, null=None, on_delete=django.db.models.deletion.CASCADE, related_name='messageimages', to='api.message'),
        ),
    ]
