# Generated by Django 5.2.1 on 2025-06-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_usernameee_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usernameee',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
