# Generated by Django 5.2.1 on 2025-06-27 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_user_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created',
        ),
    ]
