# Generated by Django 5.2.1 on 2025-06-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('dict_user', 'Dict_user'), ('find_uz_user', 'Find_uz_user')], max_length=15, null=True),
        ),
    ]
