# Generated by Django 5.2.1 on 2026-05-19 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictuser',
            name='dict_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dictuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dict_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finduzuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='find_uz_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagefile',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagefiles', to='api.message'),
        ),
        migrations.AlterField(
            model_name='messageimage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageimages', to='api.message'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='+998901234567', max_length=13, unique=True),
        ),
    ]
