# Generated by Django 5.2.1 on 2025-08-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_dictuser_is_admin_alter_dictuser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictuser',
            old_name='is_admin',
            new_name='dics_admin',
        ),
    ]
