# Generated by Django 5.2.1 on 2026-09-11 19:38

from django.db import migrations, models


def delete_finduz_users(apps, schema_editor):
    User = apps.get_model('api', 'User')
    User.objects.filter(user_type='find_uz_user').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_dictuser_dict_admin_alter_dictuser_user_and_more'),
    ]

    operations = [
        # Data: purge Find.uz accounts before dropping the Find.uz tables.
        migrations.RunPython(delete_finduz_users, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RemoveField(
            model_name='items',
            name='category',
        ),
        migrations.RemoveField(
            model_name='finduzuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='itemimages',
            name='item',
        ),
        migrations.RemoveField(
            model_name='items',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='messageimage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messagefile',
            name='message',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('dict_user', 'Dict_user')], max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='FindUzUser',
        ),
        migrations.DeleteModel(
            name='ItemImages',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='MessageImage',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageFile',
        ),
    ]
