# Generated by Django 5.2.1 on 2025-08-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_is_admin_dictuser_dics_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictuser',
            old_name='dics_admin',
            new_name='dict_admin',
        ),
    ]
