# Generated by Django 5.2.1 on 2025-09-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_dictuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default=998971234567, help_text='+998901234567', max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
