# Generated by Django 5.2 on 2025-04-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_category_country_source_diplomaticterm_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='diplomaticterm',
            name='related_countries',
            field=models.ManyToManyField(blank=True, null=True, to='dictionary.country'),
        ),
        migrations.AlterField(
            model_name='diplomaticterm',
            name='related_terms',
            field=models.ManyToManyField(blank=True, null=True, to='dictionary.diplomaticterm'),
        ),
        migrations.AlterField(
            model_name='diplomaticterm',
            name='sources',
            field=models.ManyToManyField(blank=True, null=True, to='dictionary.source'),
        ),
    ]
