# Generated by Django 5.2 on 2025-04-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_alter_category_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomaticterm',
            name='related_countries',
            field=models.ManyToManyField(blank=True, to='dictionary.country'),
        ),
        migrations.AlterField(
            model_name='diplomaticterm',
            name='related_terms',
            field=models.ManyToManyField(blank=True, to='dictionary.diplomaticterm'),
        ),
        migrations.AlterField(
            model_name='diplomaticterm',
            name='sources',
            field=models.ManyToManyField(blank=True, to='dictionary.source'),
        ),
    ]
