# Generated by Django 5.2.1 on 2026-05-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_alter_source_options_alter_source_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['-publication_date']},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='diplomaticterm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='diplomaticterm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='diplomaticterm',
            index=models.Index(fields=['-created_at'], name='dictionary__created_fdf261_idx'),
        ),
        migrations.AddIndex(
            model_name='diplomaticterm',
            index=models.Index(fields=['-updated_at'], name='dictionary__updated_1f0449_idx'),
        ),
        migrations.AddIndex(
            model_name='diplomaticterm',
            index=models.Index(fields=['category'], name='dictionary__categor_5e8b52_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['-publication_date'], name='dictionary__publica_495d89_idx'),
        ),
    ]
