# Generated by Django 5.2.1 on 2025-08-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_alter_source_options_alter_source_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diplomaticterm',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='diplomaticterm',
            name='category',
        ),
        migrations.CreateModel(
            name='DiplomaticTermPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/terms/')),
                ('term_id', models.ManyToManyField(blank=True, null=True, to='dictionary.diplomaticterm')),
            ],
        ),
        migrations.AddField(
            model_name='diplomaticterm',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='dictionary.category'),
        ),
    ]
