# Generated by Django 5.2.1 on 2025-08-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_remove_diplomaticterm_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diplomatictermphoto',
            name='term_id',
        ),
        migrations.AddField(
            model_name='diplomaticterm',
            name='photo_id',
            field=models.ManyToManyField(blank=True, null=True, to='dictionary.diplomatictermphoto'),
        ),
    ]
