# Generated by Django 5.2.1 on 2025-08-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_remove_diplomatictermphoto_term_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomaticterm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='diplomatictermphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='diplomatictermphoto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
