# Generated by Django 5.2.1 on 2025-08-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0011_alter_source_options_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomaticterm',
            name='categories',
            field=models.ManyToManyField(blank=True, to='dictionary.category'),
        ),
        migrations.AlterField(
            model_name='diplomaticterm',
            name='photo_id',
            field=models.ManyToManyField(blank=True, to='dictionary.diplomatictermphoto'),
        ),
    ]
