# Generated by Django 5.2.1 on 2025-08-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0013_alter_diplomaticterm_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomaticterm',
            name='categories',
            field=models.ManyToManyField(blank=True, to='dictionary.category'),
        ),
        migrations.AlterField(
            model_name='diplomaticterm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='diplomaticterm',
            name='definition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diplomaticterm',
            name='photo_id',
            field=models.ManyToManyField(blank=True, to='dictionary.diplomatictermphoto'),
        ),
        migrations.AlterField(
            model_name='diplomaticterm',
            name='related_countries',
            field=models.ManyToManyField(blank=True, to='dictionary.country'),
        ),
        migrations.AlterField(
            model_name='diplomaticterm',
            name='related_terms',
            field=models.ManyToManyField(blank=True, to='dictionary.diplomaticterm'),
        ),
        migrations.AlterField(
            model_name='diplomaticterm',
            name='sources',
            field=models.ManyToManyField(blank=True, to='dictionary.source'),
        ),
        migrations.AlterField(
            model_name='diplomaticterm',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='diplomaticterm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
