# Generated by Django 5.2.1 on 2025-09-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='for_whoom',
            new_name='for_whom',
        ),
    ]
