# Generated by Django 5.2.1 on 2025-09-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_rename_for_whoom_app_for_whom'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='proc_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
