# Generated by Django 5.2.1 on 2025-09-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_app_proc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='excepts',
            field=models.JSONField(default=list),
        ),
    ]
